/*
 * The MIT License (MIT)

 * Copyright (c) 2014 Michael D. Vinci

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.BrowserFactory;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.jinstagram.exceptions.InstagramException;
import twitter4j.TwitterException;

/**
 *
 * @author michaeldvinci
 */
public class LiveData extends javax.swing.JFrame {
    private String search, locatURL;
    private static GetLiveMedia glm;

    /**
     * Creates new form LiveData
     */
    public LiveData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchB = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        displayTabPane = new javax.swing.JTabbedPane();
        twitterPanel = new javax.swing.JPanel();
        instagramPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchB.setText("Search #");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });

        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout twitterPanelLayout = new javax.swing.GroupLayout(twitterPanel);
        twitterPanel.setLayout(twitterPanelLayout);
        twitterPanelLayout.setHorizontalGroup(
            twitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        twitterPanelLayout.setVerticalGroup(
            twitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        displayTabPane.addTab(" Twitter ", twitterPanel);

        javax.swing.GroupLayout instagramPanelLayout = new javax.swing.GroupLayout(instagramPanel);
        instagramPanel.setLayout(instagramPanelLayout);
        instagramPanelLayout.setHorizontalGroup(
            instagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        instagramPanelLayout.setVerticalGroup(
            instagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        displayTabPane.addTab("Instagram", instagramPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(displayTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        glm = new GetLiveMedia();
        displayTabPane.removeAll();search = searchTF.getText();
        try {
            glm.TweetCollect(search);
            glm.InstaCollect(search);
        } catch (TwitterException | InstagramException | IOException ex) {
            Logger.getLogger(LiveData.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        locatURL = "http://maps.google.com/maps/api/staticmap?zoom=1&size=700x400&maptype=roadmap";
        if((glm.getTLatitude() != 0) && (glm.getTLongitude() != 0)) {
        locatURL += "&markers=color:blue%7Clabel:T%7C" + glm.getTLatitude() + "," + glm.getTLongitude() + "&sensor=false";
        }
        if((glm.getILatitude() != 0) && (glm.getILongitude() != 0)) {
        locatURL += "&markers=color:brown%7Clabel:I%7C" + glm.getILatitude() + "," + glm.getILongitude() + "&sensor=false";
        }
        
        System.out.println(locatURL);
        
        JFrame iFrame2 = new JFrame();
        Browser browser3 = BrowserFactory.create();
        iFrame2.add(browser3.getView().getComponent(), BorderLayout.CENTER);
        browser3.loadURL(locatURL);
        iFrame2.setSize(611, 500);
        displayTabPane.addTab("  Media  ", iFrame2.getContentPane());
        
        if((glm.getTLatitude() != 0) && (glm.getTLongitude() != 0)) {
            JFrame tFrame = new JFrame();
            Browser browser = BrowserFactory.create();
            tFrame.add(browser.getView().getComponent(), BorderLayout.CENTER);
            browser.loadURL(glm.twitterURL);
            tFrame.setSize(611, 500);
            displayTabPane.addTab(" Twitter ", tFrame.getContentPane());
        }
        
        if((glm.getILatitude() != 0) && (glm.getILongitude() != 0)) {
            JFrame iFrame = new JFrame();
            Browser browser2 = BrowserFactory.create();
            iFrame.add(browser2.getView().getComponent(), BorderLayout.CENTER);
            browser2.loadURL(glm.instaURL);
            iFrame.setSize(611, 500);
            displayTabPane.addTab("Instagram", iFrame.getContentPane());
        }
    }//GEN-LAST:event_searchBActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane displayTabPane;
    private javax.swing.JPanel instagramPanel;
    private javax.swing.JButton searchB;
    private javax.swing.JTextField searchTF;
    private javax.swing.JPanel twitterPanel;
    // End of variables declaration//GEN-END:variables
}
